### ISSUE TITLE
Prebuilt for Apple Mac OS M1

### ISSUE THREAD

**Issue by DG12** [jirutka/git-metafile#2]
Being old but not Rusty,
It would be helpful if you could provide a prebuilt file for Mac OS silicon.

Thank you

**Comment by jirutka** [comment]
The x86_64 binary for macOS doesn’t work for you? I heard that Rosetta 2 is very efficient, so you shouldn’t notice any difference.

**Comment by DG12** [comment]
My oversight. It Runs. Thank you very much.
 :-)

**Comment by jirutka** [comment]
Can you please try `aarch64-apple-darwin` from https://github.com/jirutka/git-metafile/actions/runs/5987752716?
